# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dandori < Formula
  desc "Lightweight CLI outer harness for managing AI agent dev teams."
  homepage "https://github.com/phuc-nt/dandori-cli"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/phuc-nt/dandori-cli/releases/download/v0.9.0/dandori_darwin_amd64.tar.gz"
      sha256 "351fb146ead7ab02ffccdba7aaf274dcf959c4f2ac950eab6ba17790f96c2655"

      define_method(:install) do
        bin.install "dandori"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/phuc-nt/dandori-cli/releases/download/v0.9.0/dandori_darwin_arm64.tar.gz"
      sha256 "147cba02c4f6a07dd5dc5cb97aabb0853179d674809ee9c6bcf26b5282a37831"

      define_method(:install) do
        bin.install "dandori"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/phuc-nt/dandori-cli/releases/download/v0.9.0/dandori_linux_amd64.tar.gz"
      sha256 "d7f218ab12205a4d01642a1153a765d5e638adda96ff05c1cebba5d1f70e8570"
      define_method(:install) do
        bin.install "dandori"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/phuc-nt/dandori-cli/releases/download/v0.9.0/dandori_linux_arm64.tar.gz"
      sha256 "07d0851c6636be445e99a3c7358b05d0b326be17917b16263e37fc620912a9f7"
      define_method(:install) do
        bin.install "dandori"
      end
    end
  end

  test do
    system "#{bin}/dandori", "version"
  end
end
